[package]
name = "os"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "os"
path = "src/os.rs"

# this configures QEMU for testing!
# causes QEMU to exit after testing instead of continuing execution of _start() and redirecting
# test output to the hosts stdio via a serial interface. The window is not shown.
[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
# 33 = (0x10 << 1) | 1 where 0x10 is QemuExitCode::success adjusted for the QEMU exit code shifting
# this is done because cargo test assumes 0 is success, any other value is failure
test-success-exit-code = 33
test-timeout = 300 # seconds

[workspace]
members = [
    "boot",
    "os_core",
    "drivers/ata",
    "drivers/vga"
]

[dependencies]
os_core = { path = "os_core" }
vga = { path = "drivers/vga" }
ata = { path = "drivers/ata" }
bootloader = "0.10.12"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

###################################
# Register all failing tests here #
###################################
[[test]]
name = "stack_overflow"
harness = false
[[test]]
name = "page_fault"
harness = false
