[package]
name = "os"
version = "0.1.0"
edition = "2021"

[lib]
name = "os_core"
path = "src/os_core.rs"

[[bin]]
name = "os"
path = "src/os.rs"

# this configures QEMU for testing!
# causes QEMU to exit after testing instead of continuing execution of _start() and redirecting
# test output to the hosts stdio via a serial interface. The window is not shown.
[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
# 33 = (0x10 << 1) | 1 where 0x10 is QemuExitCode::success adjusted for the QEMU exit code shifting
# this is done because cargo test assumes 0 is success, any other value is failure
test-success-exit-code = 33
test-timeout = 300 # seconds

[workspace]
members = [
    "boot",
]

[dependencies]
bootloader = "0.10.12"
volatile = "0.4.4" # volatile wrapper to prevent aggressive compiler optimizations
spin = "0.9.2" # spinlock implementation
x86_64 = "0.14.9" # configures the serial port, cpu exception table
uart_16550 = "0.2.17" # serial port interface used for sending debug output to the host
noto-sans-mono-bitmap = "0.1.5" # nice bitmap font
pic8259 = "0.10.2" # interrupt controller
pc-keyboard = "0.5.1" # keyboard scan code converter

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

###################################
# Register all failing tests here #
###################################
[[test]]
name = "stack_overflow"
harness = false
