cargo-features = ["workspace-inheritance"]

[package]
name = "ata"
version = "0.1.0"
edition = "2021"

[dependencies]
internal_utils = { workspace=true }
kernel = { workspace=true }
x86_64 = { workspace=true }
spin = { workspace=true }
bitflags = { workspace=true }
lazy_static = { workspace=true }
