[build]
target = "target.json" # automatic `--target target.json` flat

[unstable]
build-std-features = ["compiler-builtins-mem"] # rebuilds the builtin memory functions without c bindings
build-std = ["core", "compiler_builtins"] # rebuilds standard library functions without c bindings

[target.'cfg(target_os = "none")']
runner = "bootimage runner" # `cargo run`

[alias]
# registers all tests in the `tests` directory
t = ["test", 
    "--test", "boot_ok",
    "--test", "invalid_vga_text_area"
]
