cargo-features = ["workspace-inheritance"]

[package]
name = "rost-lib"
version = "0.1.0"
edition = { workspace=true }

[dependencies]
internal_utils = { workspace=true }
kernel = { workspace=true }
ata = { workspace=true }
bitflags = { workspace=true }
lazy_static = { workspace=true }
