name: Build the images

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview, rust-src

      - name: Add x86_64-unknown-none target
        run: rustup target add x86_64-unknown-none

      - name: Build Images
        run: cargo kimage-r --verbose

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Build-Images
          path: /home/runner/work/rOSt/rOSt/target/x86_64-custom/release/*.img
          if-no-files-found: error
