name: Build the images

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    
    - run: rustup toolchain install nightly

    - name: Build
      run: cargo kbuild --verbose

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Build-Images
        path: ${{ github.workspace }}/target/x86_64-custom/debug/*.img
        if-no-files-found: error
