name: Build the project

on:
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:

  conditional_job_check_files:
    runs-on: ubuntu-latest
    outputs:
      source_changed: ${{ steps.changes.outputs.src }}
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - '*.rs'
            - '*.toml'
            - '*.json'

  build:
    runs-on: ubuntu-latest
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.source_changed == 'true'

    steps:
      - uses: actions/checkout@v3

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust
        run: cargo check --target x86_64-unknown-none

      - name: Install required lint crates
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload clippy results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

      - name: Build debug
        run: cargo kbuild --verbose

      - name: Build release
        run: cargo kbuild-r --verbose
